### ISSUE TITLE
[Feature Request] Vertical/Horizontal Axis & Grid Lines

### ISSUE THREAD

**Issue by NerdCowboy** [pavelkuligin/chart#13]
It's easy enough to add in, but just thought I'd throw up a request to add horizontal/vertical axis and grid lines for line, area, stacked area, stream, scatter, vert/horiz bar, and scatter graphs. 

Loving the plugin, keep up the good work!

**Comment by dnlswan** [comment]
I'm not sure how easy it would be to add but I'm also interested in this. It would certainly be a time-saver!
