### ISSUE TITLE
Parse clipboard data by stripping non-numerical characters

### ISSUE THREAD

**Issue by rayshan** [pavelkuligin/chart#15]
Hi, thanks for this plugin, very handy!

I ran into this issue: copying formatted data from Google Sheets sometimes doesn't behave well. E.g.:

Numbers with commas result in a weird looking chart:

2,692 | 2,789 | 3,001 | 3,149 | 3,489
-- | -- | -- | -- | --

![screen shot 2018-04-06 at 11 00 49 am](https://user-images.githubusercontent.com/3760840/38436574-d2b591d4-3989-11e8-991c-6354e50d47aa.png)

Numbers with dollar signs trigger the Data for Chart dialog:

$2,691.76 | $2,789.46 | $3,000.54 | $3,148.82 | $3,489.00
-- | -- | -- | -- | --

Numbers with % signs are parsed correctly.

Is it possible to parse these cases so they behave the same?

**Comment by pavelkuligin** [comment]
@rayshan problems with commas. You should delete commas because I use comma as separator. it should be $2691.76
