### ISSUE TITLE
Sparkline doesn't work.

### ISSUE THREAD

**Issue by ckizer** [pavelkuligin/chart#16]
Nothing happens when selecting sparkline.

**Comment by angaaron** [comment]
Nor does progress and solid guage charts for me.

**Comment by pavelkuligin** [comment]
@ckizer Please, try Chart 3.0. Sparkline should work well.

**Comment by ckizer** [comment]
Wow nice!! Awesome work!

**Comment by ckizer** [comment]
Okay @pavelkuligin now gauge chart doesn't work. :-)

**Comment by pavelkuligin** [comment]
@ckizer Pls send me screencast of your workflow
