### ISSUE TITLE
The plugin stopped working for no reason 🤔

### ISSUE THREAD

**Issue by ivancucer** [pavelkuligin/chart#17]
Hey @pavelkuligin 

I have no idea but the plugin stopped working for no reason... I tried everything but no luck. Take a look at the attached gif below.

Sketch 49.3 (51167) on macOS 10.12.6
Chart 2.9

![issue](https://user-images.githubusercontent.com/2349195/39097065-6785ee24-4657-11e8-976d-42b880f607ff.gif)

Any ideas ?

**Comment by pavelkuligin** [comment]
@ivancucer try two ways:
1. Copy — "test" to pasteboard and run LineChart
2. Copy:
25, 18, 39, 14, 0, 10
15, 10, 32, 24, 12, 15
and also run LineChart

**Comment by ivancucer** [comment]
@pavelkuligin thanks for your reply. Unfortunately, I have no idea how to do that 🤔 But I've found a workaround -> rebooting macOS 🙌
