### ISSUE TITLE
Charts still doesn't work

### ISSUE THREAD

**Issue by ckizer** [pavelkuligin/chart#19]
Latest Sketch v5.0
Latest Charts v3.2

Here's the video. Nothing happens. Let me know how I can help. 

Here is a video clip for download:
http://kzr.me/2K0u1s1B213M

**Comment by Christian-Baptiste** [comment]
I have several plugins not working since installing Sketch 50. Chart being one of them.

Just in case it helps here is a list that I know of so far:

Chart
Segmented Circles (all)
Craft's Duplicate
Sketch Isometric
Sketch Material - Elevation, Chips, Forms, etc. 
And counting.

**Comment by pavelkuligin** [comment]
Compatibility with Sketch 50 was restored :-)
