### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by chrispantazis** [pavelkuligin/chart#2]
Hi there,
I saw this amazing plugin and wanted to try it right away. Unfortunately is not working for me :(
I'm using sketch 48.2 on a latest Mac Os environment,  I've also tried uninstalling all other plugin except chart (it doesn't produce any errors its just that after I select the rectangle and use the plugin - tried with all charts - the rectangle stays selected but nothing else.
Regards

**Comment by pmorrow** [comment]
Looks like you have to remove the rectangle's fill to see the charts?

**Comment by chrispantazis** [comment]
Even if I do the charts are not showing.

**Comment by pavelkuligin** [comment]
@chrispantazis Please, see new explanation GIF on the Readme page.
If this doesn't work, send me your workflow screencast by email: pavel.kuligin@behavox.com

**Comment by chrispantazis** [comment]
Nothing wrong with the plugin, my mistake that I didn't create a art-board to add my rectangles on.
