### ISSUE TITLE
Build pie/donut chart based on order of data string

### ISSUE THREAD

**Issue by changecourse** [pavelkuligin/chart#21]
Currently, as far as I can tell, the donut and pie chart is built based on lowest numbers entered to highest numbers, rather than the order of the string you copy... It would be really nice to have charts built based on the order, so you can have more control in instances where slices of your chart represent linear differences (e.g., a pie chart representing the number of accounts a group may have, where you'd want the order of the chart to represent the increase of accounts around the circle)

**Comment by pavelkuligin** [comment]
@changecourse you can use Chart 3.5 and long way:
Plugins → Manage plugins → Reveal Plugins Folder → Chart.sketchplugin (right click) → Show Package Contents → Contents → Resources → params.json (open file)

Change "sortOption": "true" to "sortOption": "false"
