### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by marianneho** [pavelkuligin/chart#22]
It doesn't work for me -- doesn't generate any charts at all. 
Sketch 50.2 
Chart 3.3.0

**Comment by pavelkuligin** [comment]
@marianneho pls provide screencast of your workflow

**Comment by marianneho** [comment]
@pavelkuligin here you go: https://youtu.be/04YY55TFmyE

**Comment by Nguma** [comment]
@pavelkuligin Hi Pavel, I have the same issue
Sketch 50.2
Chart 3.3.0
Mac osX 10.11.6

**Comment by ghost** [comment]
Hi @pavelkuligin I have the same issue. Doesn't generate any charts at all, unable to set parameters.
Chart 3.3.0
Sketch 50.2
Mac osX 10.11.6

Same as @marianneho example

**Comment by thejanaki** [comment]
It stopped working for me after using Set params to change the colors and point type
Chart 3.3.0
Sketch 50.2
Mac osX 10.12.6

**Comment by philsinatra** [comment]
@pavelkuligin Similar issue. Every chart generated uses two random numbers, not the expected data that has been copied.

- Chart 3.3.0
- Sketch 50.2
- macOS 10.12.6

**Comment by phinoda** [comment]
@pavelkuligin Same issue. No chart generated at all. 
Chart 3.3.0
Sketch 50.2
Mac osX 10.11.5

**Comment by ghost** [comment]
@philsinatra & @phinoda I updated my OX to macOS High Sierra version 10.13.5 and it fixed the issue. Also sometimes copying numbers wouldn't work from Google doc so I use text editor (Sublime in my case)

**Comment by pavelkuligin** [comment]
@marianneho @Nguma @philsinatra @phinoda You should update macOS to latest version. It will fix your problems.
