### ISSUE TITLE
Insert Pie Chart and Donut Chart causes Sketch crash

### ISSUE THREAD

**Issue by BanshaTang** [pavelkuligin/chart#23]
Hi,

I can add line chart smoothly, but when I try to add a pie chart or a donut chart, there is no chart generated and Sketch will definitely crash.

Sketch version 50.2
Chart plugin version 3.3.0
macOS version 10.13.5

Thank you

**Comment by pavelkuligin** [comment]
@BanshaTang pls provide screencast of your workflow and data that you want to visualise
