### ISSUE TITLE
If selected layer is within a group, chart is created outside group

### ISSUE THREAD

**Issue by thejanaki** [pavelkuligin/chart#24]
Minor  issue - if you try to create a chart within a group in Sketch, the chart is made outside the group, and in a different position.
Sketch 50.2
Chart 3.3.0

**Comment by pavelkuligin** [comment]
@thejanaki it is the known issue and I will try to fix it later

**Comment by pavelkuligin** [comment]
I did some research about this bug and unfortunately, I can't fix it...
