### ISSUE TITLE
Adding custom colors causes plugin to not work

### ISSUE THREAD

**Issue by chrleon** [pavelkuligin/chart#25]
After I do Set Params and paste in the colors below and try to get a chart going, I only get a red line. There is no dialogbox asking me about data.

[181,1,23],[0,145,223],[104,8,102],[242,114,0],[31,37,50],[58,67,88],[255,255,255],[155,155,155],[242,242,242],[0,163,174],[253,211,0]

As I can see, the arrays are correct, right?

**Comment by pavelkuligin** [comment]
@chrleon To see dialogbox you should clean your pasteboard. To do it select any rectangle in Sketch and press cmd + C. After that you can create any chart using data from dialogbox.
