### ISSUE TITLE
Chart panel not working in Sketch 51.1

### ISSUE THREAD

**Issue by camlowe** [pavelkuligin/chart#27]
When I open the chart panel I just get a blank window, as seen below.
![screenshot 2018-07-19 14 03 12](https://user-images.githubusercontent.com/8032820/42921071-39a4ccf0-8b5d-11e8-8011-2ed7cc782c15.png)

Also get this error in the console.
```
ReferenceError: Can't find variable: dynamicFunction
line: 145
sourceURL: /Users/username/Library/Application Support/com.bohemiancoding.sketch3/Plugins/chart-master/Chart.sketchplugin/Contents/Sketch/panel.js
column: 24
```

**Comment by marcusandrew** [comment]
Yup. Same for me :( Just shows a blank window in Sketch 51 also.

**Comment by pavelkuligin** [comment]
@camlowe @marcusandrew it is known issue, but I don't know how to fix it for now...

**Comment by marcusandrew** [comment]
Thanks for the swift reply Pavel. Is it required? You can still make adjustments using the other Menu options right until a fix is found?

**Comment by utiq** [comment]
Same problem here

**Comment by ralyodio** [comment]
Same problem here.

**Comment by jbsellars** [comment]
+1, but can also confirm that charts can still be generated from the menu regular items.

**Comment by n0mar** [comment]
Status of the plugin as of Sketch Version 51.1:

* [ ] Chart Panel
* [x] **Line Chart**
* [x] **Area Chart**
* [x] **Stacked Area chart**
* [x] **Vertical Bar chart**
* [x] **Horizontal Bar chart**
* [ ] Scatter plot
* [ ] Pie chart
* [ ] Donut chart
* [ ] Stream Graph
* [ ] Sparkline
* [ ] Progress bar
* [ ] Gauge chart
* [x] **Set params**

**Comment by ivancucer** [comment]
@pavelkuligin any updates here ? 🤤

**FYI** the _workaround_ can be like this one 🙌
1. Download a _previous_ version of sketch eg. `50.2` https://download.sketchapp.com/sketch-50.2-55047.zip ⬅️
2. Unzip and _rename_ the `.app` eg. `sketch-50.2-55047` -> `sketch-50.2-55047.app` 🤓
3. Drag the app to `application` folder 📁
4. Run `50.2` along with the _current_ version of the sketch 😲 They can work **together** 😎
5. **Create** a _chart_ in `50.2` 📈
6. **Copy** it directly to the _current_ version 🎉
7. Happiness 🤤

Thanks ❤️

**Comment by KEYIIIIII** [comment]
> @pavelkuligin这里有什么更新？🤤
> 
> **仅供参考**，_解决方法_可以像这样🙌
> 
> 1. 下载_以前_版本的草图，例如。`50.2` https://download.sketchapp.com/sketch-50.2-55047.zip ⬅️
> 2. 解压缩和_重新命名_的`.app`如。`sketch-50.2-55047`- >`sketch-50.2-55047.app` 🤓
> 3. 将应用程序拖到`application`文件夹中📁
> 4. `50.2`与_当前_版本的草图一起运行😲他们可以**一起**工作**** 😎
> 5. **创建**一个_图表_中`50.2` 📈
> 6. **将**其直接**复制**到_当前_版本🎉
> 7. 幸福 🤤
> 
> 谢谢 ❤️

useful！

**Comment by pavelkuligin** [comment]
Hi there! I was on a long vacation, but right now I'm ready to fix all of these staff :-)

**Comment by pavelkuligin** [comment]
https://youtu.be/ye4PwQ8YY5A
Hi guys! I created a video to help you understand Chart's features.

**Comment by KEYIIIIII** [comment]
Can't wait

Pavel Kuligin <notifications@github.com> 于2018年9月17日周一 下午9:23写道：

**Comment by pavelkuligin** [comment]
Guys! I spent a week to figure out how to fix Panel, but nothing helps. So I decided to remove this feature in Chart 4.0.

I will try to fix it in future, sorry...

**Comment by n0mar** [comment]
@pavelkuligin, I just installed version 4.0 and nothing works. I am running Sketch 51.3 on macOS Mojave Version 10.14 (18A391)

Also worth mentioning inserting a Progress Bar is absolutely killed. It When I have a 300 width box, then I go to create the Progress Bar, the length of it came out as **3,062,571.15 pixels long**.

Not to be rude or anything, but what does 4.0 actually bring?

Thank you.

**Comment by pavelkuligin** [comment]
@n0mar Can you uninstall plugin and install it again?
I have the same version of Sketch and all works well.
Also you can send me screencast of your workflow or Conlose log of Skecth on mail: pavel.kuligin@behavox.com

![image](https://user-images.githubusercontent.com/27766810/46288255-d0445580-c58d-11e8-8109-fad049331eca.png)

**Comment by camlowe** [comment]
Appreciate the effort you've put in @pavelkuligin!
