### ISSUE TITLE
Donut and Pie Chart aren't displaying slices correctly

### ISSUE THREAD

**Issue by reddolan** [pavelkuligin/chart#29]
### Expected Behavior
chart slices should consume 100% of the radial area

![image](https://user-images.githubusercontent.com/1858226/44106742-4895ea30-9faa-11e8-8cb5-e938a14d4de2.png)

### Actual Behavior
chart slices are only taking a small portion of the radial area

![image](https://user-images.githubusercontent.com/1858226/44106655-1caca4fe-9faa-11e8-90df-a2ad817a689b.png)

### Versions
Sketch: 51.2
Chart: 3.6.0

**Comment by pavelkuligin** [comment]
@reddolan You should use data in % and total should be 100%.
In your example: 2+8+5+3+1 = 16 ≠ 100

**Comment by reddolan** [comment]
😓 doh! Thank you for pointing me in the right direction on this.
