### ISSUE TITLE
Using google sheets

### ISSUE THREAD

**Issue by HYPD** [pavelkuligin/chart#3]
Hey! Love you work! I can't seem to figure out how to import data from a google sheet. I can't seem to find the section to place the google sheets URL. Do you have instructions for this?

**Comment by pavelkuligin** [comment]
Hi Dan! Please, see attached explanation GIF.
![chart-table](https://user-images.githubusercontent.com/27766810/34513727-c7ea21be-f07a-11e7-88d5-28ffdbdab353.gif)
