### ISSUE TITLE
Categories Limited to 5?

### ISSUE THREAD

**Issue by taylorehat** [pavelkuligin/chart#30]
I have been trying to generate pie and vertical bar charts with more than 5 categories, and it's maxing out at 5 categories. It this by design?

Charts 3.6
Sketch 51.2

**Comment by pavelkuligin** [comment]
For Pie charts it is true, but you can generate Vertical bar chart with more than 5 categories. 
![image](https://user-images.githubusercontent.com/27766810/45625199-f7caf680-ba94-11e8-8315-637dde6c0d36.png)
