### ISSUE TITLE
Chart not working with Sketch 51.3

### ISSUE THREAD

**Issue by ghost** [pavelkuligin/chart#32]
Hi thanks for creating this amazing tool! Just to let you know that Chart is not working with Sketch 51.3, you have any idea?

**Comment by pavelkuligin** [comment]
@berlynnbai can you describe your workflow? Chart works for me with 51.3

**Comment by andreiinc** [comment]
Scatter plot is not working. I don't get any feedback after I set the Categories and Items.

**Comment by pavelkuligin** [comment]
@andreiinc If you see Yes in the last Dropdown in Set Params:
![image](https://user-images.githubusercontent.com/27766810/46402244-deb67c80-c707-11e8-94ff-0a79a1017a01.png)

Use Categories: 3, Items: What you want

If you see No in Set Params use Categories: 2, Items: What you want

**Comment by andreiinc** [comment]
Thank you, is working on Sketch version 51.3, but on version 52 is not working anymore.

**Comment by pavelkuligin** [comment]
They broken many API methods so for now, Chart doesn't support Sketch 52
