### ISSUE TITLE
Chart incompatible with Sketch Version 52 (66869)

### ISSUE THREAD

**Issue by n0mar** [pavelkuligin/chart#33]
Hi!

[I saw](https://github.com/pavelkuligin/chart/issues/32#issuecomment-426610091) (and experienced) Chart is incompatible with Sketch 52 (66869), so I just opened a seperate Issue.

Thank you.

**Comment by pavelkuligin** [comment]
Hi @n0mar and others!

Chart for Sketch 52 will be released in a week because I need to rewrite it for new JS API.
So I decided to charge money for all next releases of Chart. The pricing will be $10 per year. Updates every 2 weeks, new features and support.

**Comment by n0mar** [comment]
@pavelkuligin sounds reasonable! Thank you for your work!

**Comment by dariusgarza** [comment]
Thought i was going insane! Thanks much :D

**Comment by pavelkuligin** [comment]
Hi there! Chart for Sketch 52 is available now, enjoy it :-)
