### ISSUE TITLE
I only show one chart, the others are gone.

### ISSUE THREAD

**Issue by KEYIIIIII** [pavelkuligin/chart#34]
I only show one chart, the others are gone.

sketch 51.2  macos mojave

![snipaste_2018-10-08_14-03-49](https://user-images.githubusercontent.com/43202889/46594004-fffddb00-cb02-11e8-938d-35433920d6ab.jpg)

**Comment by pavelkuligin** [comment]
@KEYIIIIII Yep, Chart is paid now. You can buy the full version for $10/year or stay with a free version (line chart only). https://github.com/pavelkuligin/chart

**Comment by KEYIIIIII** [comment]
How to pay？Can I use Alipay?

Pavel Kuligin <notifications@github.com> 于2018年10月8日周一 下午2:06写道：

**Comment by pavelkuligin** [comment]
https://gumroad.com/l/sjPyY
You can use PayPal or credit card.

**Comment by KEYIIIIII** [comment]
Is there a link to payment?

Pavel Kuligin <notifications@github.com> 于2018年10月8日周一 下午2:12写道：

**Comment by pavelkuligin** [comment]
https://gumroad.com/l/sjPyY
You can pay here

**Comment by KEYIIIIII** [comment]
ok

Pavel Kuligin <notifications@github.com> 于2018年10月8日周一 下午4:03写道：

**Comment by KEYIIIIII** [comment]
Solve all the bugs?

顾思杰 <gusijielife@gmail.com> 于2018年10月8日周一 下午4:03写道：

**Comment by pavelkuligin** [comment]
Yep, it works in Sketch 52 and 52.1. And new features are coming :-)
Also, you can find video tutorials here: https://github.com/pavelkuligin/chart

**Comment by KEYIIIIII** [comment]
thx  I think you can open Alipay, so Chinese users will be more convenient.

Pavel Kuligin <notifications@github.com>于2018年10月8日 周一16:06写道：
