### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by WimoApp** [pavelkuligin/chart#35]
I managed to generate couple of charts, then the plugin stopped to function, i put the same number of categories and items and i click, nothing happens

**Comment by pavelkuligin** [comment]
@WimoApp can you provide more details? You can send me a screencast of your workflow by email: pavel.kuligin@behavox.com

**Comment by alechp** [comment]
@pavelkuligin I'm also having inconsistency. Uploaded screencast here: https://goo.gl/JS2gNn

**Comment by pavelkuligin** [comment]
@alechp 
1. You can't select the whole Artboard, only rectangle and oval shape are allowed.
2. I think it is a bug with random data generation. I've fixed it yesterday and I will push new version with bug fixes and new features on Saturday.

**Comment by alechp** [comment]
@pavelkuligin Since your latest update, haven't noticed any issues 👍 Thank you
