### ISSUE TITLE
Pie charts only rendering half circle regardless of data values

### ISSUE THREAD

**Issue by Shredivan** [pavelkuligin/chart#39]
![screenshot 2019-01-24 at 10 29 00](https://user-images.githubusercontent.com/14276542/51672403-4cdac400-1fc3-11e9-92aa-dde772269216.png)

Having issues with creating pie charts where half a circle renders regardless of the data that is inputted

**Comment by pavelkuligin** [comment]
@Shredivan pls share your data

**Comment by Shredivan** [comment]
@pavelkuligin I've tried many variations of this to ensure It wasn't the format of data I was adding to it.

![screenshot 2019-01-31 at 14 24 26](https://user-images.githubusercontent.com/14276542/52060357-eece5380-2563-11e9-8134-9d447a1932e5.png)

**Comment by pavelkuligin** [comment]
@Shredivan problem could be with the color palette. Please, send me screenshot of Set Params popup

**Comment by Shredivan** [comment]
@pavelkuligin Here you go.

![screenshot 2019-01-31 at 14 35 52](https://user-images.githubusercontent.com/14276542/52061122-8a13f880-2565-11e9-981c-92f741ef1f25.png)

**Comment by pavelkuligin** [comment]
@Shredivan Paste this in the Colors field: ["44","126","177"],["107","192","132"],["249","212","102"],["236","104","77"],["133","100","197"]

**Comment by Shredivan** [comment]
@pavelkuligin That seemed to fix it

**Comment by pavelkuligin** [comment]
@Shredivan Pls read how to manage colors easily: https://medium.com/sketch-app-sources/chart-4-5-or-panel-return-history-5b47da757754
