### ISSUE TITLE
No params dialog and "must contain 2 or more points"

### ISSUE THREAD

**Issue by MintCondition** [pavelkuligin/chart#40]
Plugin was working fine, and then ceased working. Select shape, choose chart type. No dialog for number of cats or items shows up and an error message appears stating the "chart must contain 2 or more points." 

Have tried uninstalling and reinstalling, as well as multiple documents. 

Ideas?

**Comment by pavelkuligin** [comment]
@MintCondition This notification means that plugin tried to visualize data from your pasteboard. This bug will be resolved in the next release (soon). For now, you can press CMD+C on the shape (it will clear your pasteboard).

**Comment by MintCondition** [comment]
THANK YOU! No idea it was so simple. I did manage to "fix it" by restarting (which obv solved it). Next time it happens I'll just do that instead. 

Kudos, you make so much of what I'm working on easier! =)

**Comment by pavelkuligin** [comment]
You are welcome! :-)
