### ISSUE TITLE
Create Multiple Charts at a time

### ISSUE THREAD

**Issue by SimplyPhy** [pavelkuligin/chart#43]
<img width="655" alt="Screenshot 2019-06-06 14 37 58" src="https://user-images.githubusercontent.com/7506223/59057651-da2efe80-8868-11e9-8434-e5f0c06af97f.png">

I would love to be able to select multiple rectangles at a time to generate charts with random data.

**Comment by pavelkuligin** [comment]
Hi @SimplyPhy! It is possible, but not for all Chart types. Need to think about the possibility to allow it for all types

**Comment by SimplyPhy** [comment]
Any chance of packing this with v5.1, at least for some of the basic charts (line/bar)?  I usually need to create at least a few charts at a time for initial mockups.  I'm about to fill out a design that needs 20 of the same chart with slightly different data (same scope, different randomly generated values).  And I'll likely need to do a few versions of it.

**Comment by pavelkuligin** [comment]
@SimplyPhy will do my best to deliver it in 5.1
