### ISSUE TITLE
Error while trying to use external json

### ISSUE THREAD

**Issue by raulfunkie** [pavelkuligin/chart#45]
I'm getting these errors when trying to use one of the supplied (or any) external json.

I'm using "Inspect Element" on the Graph spinner window to see the console errors.

![Screen Shot 2019-06-10 at 2 25 06 PM](https://user-images.githubusercontent.com/15929687/59217397-dadad400-8b8b-11e9-9ef8-730d574d821b.png)

**Comment by pavelkuligin** [comment]
Hi @raulfunkie! The error linked with your network settings (for me it works well). There is no simple answer or fix, but I will investigate possible solutions. Anyway, you can download JSON and use it as Local JSON.
