### ISSUE TITLE
Copy Paste Google Spreadsheet doesn't take all Values creates new Rows

### ISSUE THREAD

**Issue by janjuno** [pavelkuligin/chart#46]
When I copy paste or connect via share link not all values are imported correctly instead it will create another additional row and fill it up.

I work with finance data and they need to be correct and exact. 

![Bildschirmfoto 2019-07-17 um 20 02 47](https://user-images.githubusercontent.com/13254959/61399216-f42f1880-a8cd-11e9-9d99-536ba4e0e2fc.png)

**Comment by pavelkuligin** [comment]
@jansemka could you pls share link to GS for testing?

**Comment by janjuno** [comment]
Last Column was GP. 5 Rows. Count of digits you can see above. First Table Row. I won't share these are client data.

**Comment by janjuno** [comment]
I got it running btw. I used the JSON import. I think the issue is that the plugin table isn't using endless rows, it will break at some point and fill it up.

**Comment by pavelkuligin** [comment]
@jansemka Yes, you are right, there is a problem with performance and I limit the number of columns to 100. If you want to use big datasets you can use JSON, as you did.
