### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by ivancucer** [pavelkuligin/chart#47]
Hey @pavelkuligin 

Do you have any plans to support Figma when figma's API for `plugins` will be available ?

Unfortunately, Bohemian team moves very slow with their sketch and I really think to jump to Figma very soon.

Thanks,
Ivan

**Comment by pavelkuligin** [comment]
@ivancucer Sure, I'm working on it right now and I expect that Chart will be available in August.
It will be free until the end of the year and then you can use your subscription for Chart, no need to pay twice.
