### ISSUE TITLE
Cannot install plugin on Sketch Version 57.1 (83088)

### ISSUE THREAD

**Issue by floragreste** [pavelkuligin/chart#48]
Tried to install your plugin via Runner and it does not work. Tried via GitHub and it does not work either. I am attaching a screenshot of the unzipped files I get after unzipping the zip. Can you fix it? Thanks for your help.

<img width="243" alt="Screenshot 2019-08-16 at 14 56 18" src="https://user-images.githubusercontent.com/28628830/63172927-b2ad9c80-c036-11e9-8c87-ac22cc53d9be.png">

**Comment by pavelkuligin** [comment]
@floragreste The only way to install plugin is to download it from official page: https://pavelkuligin.ru/chart/

Note: Chart is paid plugin and you need to subscribe. I will release new version with trial period at the end of month.
