### ISSUE TITLE
Coma vs. Point Values

### ISSUE THREAD

**Issue by janjuno** [pavelkuligin/chart#49]
In Germany we would write Currency like this:

30,05 €

in English you would write:

30.05 $

I got charts now like this:
![image](https://user-images.githubusercontent.com/13254959/65873243-e5131f00-e382-11e9-9868-99fa4af9317e.png)

**Comment by janjuno** [comment]
As Addition here with corrected data:
![image](https://user-images.githubusercontent.com/13254959/65873813-68814000-e384-11e9-8800-42e84daf61c9.png)

**Comment by pavelkuligin** [comment]
Thanks @jansemka! I will add a feature to parse different number formats

**Comment by pavelkuligin** [comment]
@jansemka issue fixed in Chart 5.4.0 for Sketch
