### ISSUE TITLE
Line chart not working with negative valies

### ISSUE THREAD

**Issue by florianpeninon** [pavelkuligin/chart#5]
I noticed that the line chart wasn't working with negative values, it renders a flat line (I didn't try any other type of chart)

I used a work-around that might help you to solve the issue, I used the absolute numbers and then flip the line vertically to get it right.

**Comment by pavelkuligin** [comment]
Thanks, Florian! Negative numbers will be supported in Chart 2.6

**Comment by pavelkuligin** [comment]
@florianpnn Pls, update Chart and enjoy negative values :-)

**Comment by florianpeninon** [comment]
Thanks!
Keep up the good work!

**Comment by iMomen** [comment]
Hello, 
I can't see the negative values working for the Vertical bar chart, Do I missed something?

![image](https://user-images.githubusercontent.com/5030329/66697210-453b8680-ecdc-11e9-9bd5-cd4958bb38a8.png)

**Comment by pavelkuligin** [comment]
@iMomen Stacked bar chart couldn't work with negative values. Only bar chart with 1 category supports negative values:
![image](https://user-images.githubusercontent.com/27766810/66702828-cb0a0280-ecd9-11e9-96bf-9e0361bd7688.png)

**Comment by iMomen** [comment]
Excellent, is there is any ability to change the negative values color?

**Comment by pavelkuligin** [comment]
@iMomen for now you can do it only manually, it is a good feature — will add it to the backlog
