### ISSUE TITLE
Bubble Charts missing?

### ISSUE THREAD

**Issue by SirWellington** [pavelkuligin/chart#51]
![image](https://user-images.githubusercontent.com/992646/70104750-de5b8f00-15f3-11ea-8428-6e4bb183755a.png)

How can I make a bubble chart? I can't see the option to make a Bubble chart anymore. How can I make it so that the dots generated vary in diameter?

**Comment by pavelkuligin** [comment]
@SirWellington Hi! Option for Bubbles has been added in Chart 5.4.0 for Sketch
