### ISSUE TITLE
Syncing JSON API will not work

### ISSUE THREAD

**Issue by FrankwenRJ** [pavelkuligin/chart#53]
Hey,

Just got the trial version and everything looks awesome. When trying to connect our REST API from SQL DB, the Syncing process just goes on forever. Is this because I did not pay for the license or is this a problem elsewhere? Any support would be really appreciated. Thanks

REST API: http://www.rjclothing.cn/rojoipad/index.php/api/chart/product_sales

**Comment by FrankwenRJ** [comment]
Sketch Version 61.2 (89653)
Mac OS 10.15.3 
Mac OS 10.13.4 

Both with same issue

**Comment by pavelkuligin** [comment]
@FrankwenRJ  hey! Your API returns JSON in incompatible format. Read more here: https://pavel-kuligin.gitbook.io/chart/json-data

So your JSON should look like this:
[{"status":"103","statusmsg":"parameter error"}]

Instead of this:
{"status":"103","statusmsg":"parameter error"}

**Comment by FrankwenRJ** [comment]
Hey man, okay got it, very clear. Will try to correct for that. Thanks a million for the quick reply, plugin is amazing and will use it to create full BI dashboard system. Cheers

**Comment by pavelkuligin** [comment]
You are welcome! Join our Slack channel for faster support: https://join.slack.com/t/chart-plugin/shared_invite/enQtNDc0MTYzMTE5MzkzLTBiNDRjMTYzMTQ5NGYxMjg0MGY4ODJiZmJmNWRiNTc0YzhjOThmY2M2NmU0MTYwZTdhNzhmZGRhZjM2MzRkYzI
