### ISSUE TITLE
[Feature Request] Continual Graph Update

### ISSUE THREAD

**Issue by dcliftreaves** [pavelkuligin/chart#54]
Ideally graph updating would be done quickly and performant-ly to allow for real time graph visualizations. But, before that is possible, is it possible to have a menu option to just update the graph every second until that option is de-selected?

**Comment by pavelkuligin** [comment]
Hi David! Unfortunately, plugin in Sketch or Figma cannot work in background to run this task on some schedule.

**Comment by dcliftreaves** [comment]
I understand that the constraints of the framework you are in do not allow for this behavior. 

Can you create an automator task that does this for your customers to install in a simple way?

Example:
https://macmost.com/3-ways-to-automate-keystroke-sequences-on-your-mac.html

**Comment by pavelkuligin** [comment]
The only way to resolve it is use current Update chart feature. I have a plan to introduce bulk update in case if you have more then one chart on the page. I plan to introduce it in this quarter.

**Comment by dcliftreaves** [comment]
Ah the bulk update is required for my auto refresh idea via Automator to
work.

**Comment by pavelkuligin** [comment]
Hi @dcliftreaves can you join our Slack and ping me, so we can discuss your idea in more details: https://join.slack.com/t/chart-plugin/shared_invite/zt-61tsh8gx-C0TBYxSU8ShA~IK_v121dA
