### ISSUE TITLE
Improve documentation and verbiage around usage

### ISSUE THREAD

**Issue by dannykansas** [pavelkuligin/chart#6]
I've seen quite a few posts about this plugin around the web that had the same issue I experienced: you have to copy data _to the clipboard_ in order to successfully generate a chart. 

I'll be submitting a PR with some updates to usage; hopefully this will aid others who encountered the same issue of seeing "Generate Random Data" due to simply highlighting data in their canvas rather than copying it to the clipboard.

**Comment by pavelkuligin** [comment]
Hi, Danny! Will wait for you PR, thanks! 
I also thought about adding import data from JSON/CSV, but I'm not sure if this useful.
