### ISSUE TITLE
No response when using

### ISSUE THREAD

**Issue by seobaby** [pavelkuligin/chart#61]
No response when using and can't update version 4.3
- Bundle Identifier: com.bohemiancoding.sketch3 
- Build Version: 72.4 
- Build Number: 124482 
- OS Version: 11.5.2 
- CPU Type: X86 
- Rosetta: No

**Comment by seobaby** [comment]
> No response when using，and can't update version 4.3
> 
> * Bundle Identifier: com.bohemiancoding.sketch3
> * Build Version: 72.4
> * Build Number: 124482
> * OS Version: 11.5.2
> * CPU Type: X86
> * Rosetta: No

**Comment by pavelkuligin** [comment]
Hello @seobaby ! Please use the latest version of Chart plugin: https://chartplugin.com/
