### ISSUE TITLE
Does not work in the latest sketch

### ISSUE THREAD

**Issue by neoighodaro** [pavelkuligin/chart#62]
I get this error when i try to generate a chart with random data and default values:

```TypeError: element.childNodes[j].setAttribute is not a function. (In 'element.childNodes[j].setAttribute('DragObj', cDrag)', 'element.childNodes[j].setAttribute' is undefined)```

Device: Mac M1 Pro 14"
Sketch: Version 79.1 (133344)
Plugin list:
<img width="245" alt="Screenshot 2021-11-12 at 09 12 15" src="https://user-images.githubusercontent.com/807318/141433185-c7838a22-0798-4692-8d62-366c299e6f98.png">

**Comment by FrankFlitton** [comment]
I also see the error. It hangs on the drawing screen.

```
TypeError: element.childNodes[j].setAttribute is not a function. (In 'element.childNodes[j].setAttribute('DragObj', cDrag)', 'element.childNodes[j].setAttribute' is undefined)
```

This also happened with tabular as well as random data.

Device: 2019 Intel Core i9 16"
Sketch: Version 73.1 (127209) as well as latest 80.1
Plugin list:
![image](https://user-images.githubusercontent.com/8129392/144961388-e54bbce9-3a66-4c5e-9f08-5c9e28917547.png)

**Comment by FrankFlitton** [comment]
Update: It seems to work with the area chart but not line chart.

**Comment by pavelkuligin** [comment]
Hey @FrankFlitton and @neoighodaro please download the updated version 5.6.6 from official website: https://chartplugin.com/. The issue should be fixed

**Comment by FrankFlitton** [comment]
Awesome, thanks!

![image](https://user-images.githubusercontent.com/8129392/145147423-7d26ba51-3d28-4901-81f1-e753cf26504c.png)
