### ISSUE TITLE
Can't update to version 2.6

### ISSUE THREAD

**Issue by thischrisoliver** [pavelkuligin/chart#7]
Sketch is showing me that version 2.6 is available for updating, but if I click the Update button in the preferences, nothing happens.

I checked Sketch Runner, but it's actually showing that 2.5 is the latest version with no update available.

I tried downloading the zip and manually installing the plugin, but then I got a warning asking if I wanted to replace version 2.5 with 2.5, which doesn't make since the new version is 2.6.

<img width="532" src="https://user-images.githubusercontent.com/22454900/35530571-7c25ef0a-0502-11e8-85a9-567fe884f934.png">

**Comment by pavelkuligin** [comment]
Hi @thischrisoliver! It was my mistake... Chart is already fixed and you can download version 2.7 or use Sketchpacks. Thank you for your immediate feedback!
